language: php
dist: trusty

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

cache:
    directories:
        - ./vendor/
sudo: false

before_script:
  - sh -c "composer install --dev --no-progress"
 
script: 
    - phpunit

branches:
  only:
    - develop
    - master
